<?php
session_start();
require_once '../config/config.php';
if(!isAdmin()) { header('Location: login.php'); exit; }
$totalProducts = $pdo->query("SELECT COUNT(*) FROM products")->fetchColumn();
$totalOrders = $pdo->query("SELECT COUNT(*) FROM orders")->fetchColumn();
$pendingOrders = $pdo->query("SELECT COUNT(*) FROM orders WHERE payment_status='pending'")->fetchColumn();
$completedOrders = $pdo->query("SELECT COUNT(*) FROM orders WHERE order_status='delivered' OR order_status='completed'")->fetchColumn();
$lowStock = $pdo->query("SELECT COUNT(*) FROM products WHERE stock_quantity<10 AND stock_quantity>0")->fetchColumn();
$outOfStock = $pdo->query("SELECT COUNT(*) FROM products WHERE stock_quantity=0")->fetchColumn();
$totalSales = $pdo->query("SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE payment_status='completed'")->fetchColumn();
$recentOrders = $pdo->query("SELECT * FROM orders ORDER BY created_at DESC LIMIT 5")->fetchAll();
?>
<!DOCTYPE html>
<html><head><title>Admin Dashboard - African Fashion</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"><style>.sidebar{min-height:100vh;background:#1a1a2e;}.sidebar .nav-link{color:white;padding:12px20px;}.sidebar .nav-link:hover,.sidebar .nav-link.active{background:#f36f25;}.stat-card{padding:20px;color:white;margin-bottom:20px;border-radius:10px;}</style></head>
<body><div class="container-fluid"><div class="row"><div class="col-md-2 p-0 sidebar"><div class="text-center py-3"><h5 class="text-white"><i class="fas fa-tshirt"></i> African Admin</h5></div><nav class="nav flex-column"><a class="nav-link active" href="index.php"><i class="fas fa-tachometer-alt"></i> Dashboard</a><a class="nav-link" href="products.php"><i class="fas fa-box"></i> Products</a><a class="nav-link" href="orders.php"><i class="fas fa-shopping-cart"></i> Orders</a><a class="nav-link" href="inventory.php"><i class="fas fa-warehouse"></i> Inventory</a><a class="nav-link" href="logout.php"><i class="fas fa-sign-out-alt"></i> Logout</a></nav></div><div class="col-md-10 p-4"><div class="d-flex justify-content-between"><h2>Welcome, <?php echo htmlspecialchars($_SESSION['admin_user']); ?></h2><a href="../index.php" target="_blank" class="btn btn-primary">View Store</a></div><div class="row mt-4"><div class="col-md-3"><div class="stat-card" style="background:#f36f25;"><i class="fas fa-box fa-2x"></i><h3><?php echo $totalProducts; ?></h3><p>Total Products</p></div></div><div class="col-md-3"><div class="stat-card" style="background:#28a745;"><i class="fas fa-shopping-cart fa-2x"></i><h3><?php echo $totalOrders; ?></h3><p>Total Orders</p></div></div><div class="col-md-3"><div class="stat-card" style="background:#ffc107;color:#333;"><i class="fas fa-clock fa-2x"></i><h3><?php echo $pendingOrders; ?></h3><p>Pending Orders</p></div></div><div class="col-md-3"><div class="stat-card" style="background:#17a2b8;"><i class="fas fa-chart-line fa-2x"></i><h3><?php echo formatPrice($totalSales, 'USD'); ?></h3><p>Total Revenue (USD)</p></div></div></div><div class="row mt-4"><div class="col-md-6"><div class="card"><div class="card-header bg-warning"><h5><i class="fas fa-exclamation-triangle"></i> Stock Alerts</h5></div><div class="card-body"><p><strong>Low Stock (&lt;10):</strong> <?php echo $lowStock; ?> products</p><p><strong>Out of Stock:</strong> <?php echo $outOfStock; ?> products</p><a href="inventory.php" class="btn btn-warning">Manage Inventory</a></div></div></div><div class="col-md-6"><div class="card"><div class="card-header bg-primary text-white"><h5><i class="fas fa-clock"></i> Recent Orders</h5></div><div class="card-body"><?php foreach($recentOrders as $order): ?><div class="border-bottom pb-2 mb-2"><strong><?php echo $order['order_number']; ?></strong> - <?php echo $order['customer_name']; ?><br><small><?php echo date('M d, H:i', strtotime($order['created_at'])); ?></small></div><?php endforeach; ?><a href="orders.php" class="btn btn-primary btn-sm">View All Orders</a></div></div></div></div></div></div></div></body>
</html>